# .github/workflows/deploy.yml
# https://docs.github.com/en/actions/using-jobs/defining-outputs-for-jobs
name: Deploy API

# the event that will trigger the action
on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: 'Environment'
        required: true
        default: 'prod'

env:
  NODE_ENV: ${{ github.event.inputs.environment }}

jobs:
  deploy-staging:
    strategy:
      matrix:
        node-version: [19]
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    # Create an environment
    environment:
      name: ${{ github.event.inputs.environment }}
      url: ${{ steps.renderUrl.outputs.url }}

    outputs:
      url: ${{ steps.renderUrl.outputs.url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.4
        with:
          version: 8.1.0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Deploy to Render Using Webhook
        run: |
          curl -X GET "${{ secrets.DEPLOYMENT_WEBHOOK_RENDER }}"
        continue-on-error: false

      - name: Render host url
        id: renderUrl
        env:
          HOST_URL: "https://resume-${{ github.event.inputs.environment }}-f54f.onrender.com"
        run: |
          echo "::set-output name=url::${{ env.HOST_URL }}"
