# .github/workflows/push.yml
name: Build Checks
on:
  push:
    branches:
      - master

jobs:
  build_checks:
    name: Build Checks CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set the correct Node version using nvm
        shell: bash -l {0}
        run: nvm install

      - name: Install npm packages
        run: |
          npm install

      - name: Run convert file
        run: |
          npm run convert -- src/examples/index.html out/index.pdf --data '{"name": "Your Name", "dateformat": "MMM YYYY", "title": "Lorem ipsum dolor."}'

      - name: Check file existence
        id: check_files
        uses: andstor/file-existence-action@v2
        with:
          files: "out/index.pdf"
          allow_failure: false

      - name: File doesn't exists
        if: steps.check_files.outputs.files_exists != 'true'
        run: exit 1

      - name: File exists
        run: echo "Successfully, Generated the file."